var lines = [
	"Is your name Google? Because you have everything I've been searching for.",
	"You make my software turn into hardware!",
	"Is your name Wi-fi? Because I'm really feeling a connection.",
	"Are you sitting on the F5 key? Cause your ass is refreshing.",
	"You had me at 'Hello World.'",
	"Want to see my HARD Disk? I promise it isn't 3.5 inches and it ain't floppy.",
	"You can put a Trojan on my Hard Drive anytime.",
	"You still use Internet Explorer? You must like it nice and slow.",
	"I hope you're an ISO file, because I'd like to mount you.",
	"My servers never go down... but I do!",
	"My 'up-time' is better than BSD.",
	"Are you an angel, because your texture mapping is divine!",
	"You've stolen the ASCII to my heart.",
	"Are you a computer keyboard? Because you're my type.",
	"You got me stuck on Caps Lock, if you know what I mean.",
	"If you were a web browser, you'd be called a Fire-foxy lady",
	"How about we do a little peer-to-peer saliva swapping?",
	"Mind if I run a sniffer to see if your ports are open?",
	"Your beauty rivals the graphics of Call of Duty.",
	"You must be Windows 95 because you've got me feeling so unstable.",
	"I was hoping you wouldn't block my pop-up.",
	"Want to see my Red Hat?",
	"If you won't let me buy you a drink, at least let me fix your laptop.",
	"You put the SPARC in my workstation.",
	"You're so pretty, I wouldn't even need to use an Instagram filter if I took your photo.",
	"Isn't your e-mail address beautifulguy@mydreams.com?",
	"I'd switch to emacs for you.",
	"What's a nice guy like you doing in a chatroom like this?",
	"No, that's not a Logitech MX-100 in my pants, but thanks for noticing.",
	"Nice Set of Floppies!",
	"I think you could be an integral part of my project life cycle.",
	"If you have an empty slot, I have the card to fill it.",
	"WebMD says your love is contagious.",
	"Hey, how 'bout I take off your cover and insert a bigger CPU.",
	"I'd like to play on your laptop.",
	"Where's the 'like' button for that smile?",
	"You totally spiked my traffic.",
	"You are the Apple of my i-Mac.",
	"If you were an ISP I'd dial you all day long.",
	"If you were an ebay auction, I'd totally 'buy it now'.",
	"You have a trojan? hmm... I think I'll need to take a look at that backdoor.",
	"Come to my 127.0.0.1 and I'll give you sudo access.",
	"I must be using Apple maps, because I keep getting lost in your eyes.",
	"I'd get a T3 to watch your streaming video.",
	"I'll bet my hard drive is the biggest you've ever seen.",
	"Your homepage or mine?",
	"Hey Baby, Let me hack your kernel.",
	"No, that's not an iPod mini in my pocket. I'm just happy to see you.",
	"You auto-complete me.",
	"I didn't mean to ogle you, but I'd sure like to Google you.",
	"I was wondering if you'd like to go back to My-Space, so I can Twitter with your Yahoo, until I Google all over your Facebook?",
	"If you ever need to get rid of a trojan, don't hesitate to call me!",
	"You're making me feel like I have something in common with these pop-up ads.",
	"What's the difference between a crush and a Facebook account? I'm not rapidly developing a Facebook account on you.",
	"I need to hop over to Facebook for a second to change my status to smitten.",
	"What do you say we play a game of 'Words With More Than Friends?'",
	"Roses are #ff0000, violets are #0000ff, all my base are belong to you.",
	"Need me to unzip your files?",
	"Are your pants a compressed file? Because I'd love to unzip them!",
	"I googled your name earlier... I clicked on 'I'm Feeling Lucky.'",
	"How about we go home and you handle my exception?",
	"If we were connected on Linkedin, I'd endorse you all night long.",
	"I wish you were Broadband, so I could get high-speed access.",
	"You are hotter than the bottom of my laptop.",
	"I'd ask if you come here often, but I already stalk you on FourSquare.",
	"Computer techs have skilled fingers if you know what I mean."
];